#!/bin/bash

DEBUG=yes

debug () {
	[ "$DEBUG" == yes ] && echo "$@" >&2
	"$@"
}

BOTTLES="$HOME/.bottles"
WINEVERSIONS="$BOTTLES/.wineversions"

mkdir -p "$WINEVERSIONS"

NAME=bottle
VERSION=0.01
USAGE="$0 [cmd] [bottle] <args...>

	create         	Creates a new bottle
	list           	Show all bottles already created
	run            	Runs a command within the bottle
	script         	Prints the shell script used to run the bottle
	configure      	Runs winecfg in the bottle
	install-version	Downloads an older version of wine
	versions       	Lists versions of wine available for download
"

bottle.script() {
	source "$WINEPREFIX/bottle-settings"
	echo "#!/bin/bash"
	if [ -n "$WINEVERSION" ]; then
		echo "PATH=$WINEVERSIONS/$WINEVERSION/usr/bin/:\$PATH"
	fi
	echo export WINEPREFIX=\"$WINEPREFIX\"
	echo export WINEDEBUG=\"-all\"
	DIR="$(dirname "$(winepath -u "$EXE")")"
	echo cd \"$DIR\"
	echo wine \"$EXE\" \"\$@\"
}

bottle.config() {
	echo "#!/bin/bash"
	if [ -n "$WINEVERSION" ]; then
		echo "PATH=$WINEVERSIONS/$WINEVERSION/usr/bin/:\$PATH"
	fi
	echo export WINEPREFIX=\"$WINEPREFIX\"
	echo winecfg
}

abort () {
	echo "$USAGE"
	exit 1
}

bottle.create () {
	debug env WINEPREFIX="$WINEPREFIX" wineboot -u
}

bottle.versions () {
	debug wget -q -O- http://mulx.playonlinux.com/wine/linux-i386/LIST | cut -d';' -f2
}

depend_wine_version () {
	bottle.checkversion "$1" || bottle.installwine "$1"
}

bottle.checkversion () {
	[ -d "$WINEVERSIONS/$1" ]
}

bottle.installwine () {
	debug wget -q http://mulx.playonlinux.com/wine/linux-i386/PlayOnLinux-wine-$1.pol -O- | debug tar -xjP --exclude=files --exclude=playonlinux --transform "s|wineversion|$WINEVERSIONS|"
}

CMD="$1"
if [ -n "$2" ]; then
	WINEPREFIX="$BOTTLES/$2"
	source "$WINEPREFIX/bottle-settings"
fi
case "$CMD" in
	create)
		shift 2
		create "$@"
		;;
	run)
		shift 1
		depend_wine_version "$WINEVERSION"
		bottle.script "$@" | /bin/bash
		;;
	configure)
		shift 1
		bottle.config | /bin/bash
		;;
	list)
		ls "$BOTTLES"
		;;
	script)
		shift 1
		bottle.script "$@"
		;;
	versions)
		bottle.versions
		;;
	install-version)
		shift 1
		bottle.installwine "$@"
		;;
	-v|--version)
		echo "$NAME $VERSION"
		;;
	*)
		abort
		;;
esac
