#!/usr/bin/env python

from bottle import *

OFFICEPATH = 'C:/Program Files/Microsoft Office/OFFICE11/'
WORDPATH = OFFICEPATH + 'WINWORD.EXE'
EXCELPATH = OFFICEPATH + 'EXCEL.EXE'
PPOINTPATH = OFFICEPATH + 'POWERPNT.EXE'

@Installer('office', '1.0')
def install(office):
	#Perform the installation
	setup_exe = office.AddInstallSource(cd='Setup.exe', note='Setup.exe on the main CD')
	office.AddCommand(setup_exe)

	#Extract all important icons
	word_ico = office.AddIco(exe=WORDPATH, name='1')
	word_doc_ico = office.AddIco(exe=WORDPATH, name='2')
	excel_ico = office.AddIco(exe=EXCELPATH, name='257')
	excel_doc_ico = office.AddIco(exe=EXCELPATH, name='258')
	ppoint_ico = office.AddIco(exe=PPOINTPATH, name='1300')
	ppoint_doc_ico = office.AddIco(exe=PPOINTPATH, name='1301')

	#Let's default to launching word
	office.settings.EXE = WORDPATH
	office.settings.word = '''run('wine', %r, *[windowspath(a) for a in argv[1:]])''' % WORDPATH
	office.settings.excel = '''run('wine', %r, *[windowspath(a) for a in argv[1:]])''' % EXCELPATH
	office.settings.powerpoint = '''run('wine', %r, *[windowspath(a) for a in argv[1:]])''' % PPOINTPATH

	#Application launchers
	office.AddDesktop('Microsoft Word', word_ico, exe='word', categories=('Office',))
	office.AddDesktop('Microsoft Excel', excel_ico, exe='excel', categories=('Office',))
	office.AddDesktop('Microsoft Powerpoint', ppoint_ico, exe='powerpoint', categories=('Office',))
	#Support for opening files through a freedesktop.org file browser
	office.AddDesktop('Microsoft Word', word_doc_ico, exe='word %F', 
	  mimetype='application/msword', nodisplay=True, startupnotify=True)
	office.AddDesktop('Microsoft Excel', excel_doc_ico, exe='excel %f',
	  mimetype='application/vnd.ms-excel', nodisplay=True, startupnotify=True)
	office.AddDesktop('Microsoft Powerpoint', ppoint_doc_ico, exe='powerpoint %f',
	  mimetype='application/vnd.ms-powerpoint', nodisplay=True, startupnotify=True)
