#!/usr/bin/env python

from bottle import *
import sys

bottle_settings = '''
WINEVERSION='0.9.14'
EXE="C:/Program Files/Starcraft/StarCraft.exe"

def update():
	import os
	import re
	
	avail = download('http://ftp.blizzard.com/pub/broodwar/patches/PC/')
	patches = ['http://ftp.blizzard.com' + match.group(1) for match in re.finditer('<A HREF="(.*?)">', avail) if match.group(1).endswith('.exe')]
	latest = sorted(patches, key=lambda x:x.replace('_','-'))[-1]
	name = os.path.split(latest)[1]
	
	with WorkingDir(WINEPREFIX):
		if name not in os.listdir('.'):
			print 'Getting patch', name
			download(latest, name)
			print 'Applying patch'
			run('wine', name)
		else:
			print 'Already at the latest version:', name
'''

sc = Installer('starcraft')
sc.settings(bottle_settings)

starcraft = sc.AddInstallSource('starcraft-setup.exe', 'Setup.exe from the Starcraft CD')
broodwar = sc.AddInstallSource('broodwar-setup.exe', 'Setup.exe from the Brood War CD')

sc.AddCommand('run', starcraft)
sc.AddCommand('copy', starcraft, WinePath('c:/Program Files/Starcraft/Starcraft.mpq').toUnix())
sc.AddCommand('run', broodwar)
sc.AddCommand('copy', broodwar, WinePath('c:/Program Files/Starcraft/Broodwar.mpq').toUnix())
sc.AddCommand('run','update')

sc.AddIco('starcraft.ico', exe='c:/Program Files/Starcraft/StarCraft.exe', name='102')
sc.AddDesktop('Starcraft: Brood War', 'starcraft.ico', categories='Application;Game;')

sc.Go(sys.argv)
