#!/usr/bin/env python

from bottle.installer import *

update = '''import os, re
avail = open(download('http://ftp.blizzard.com/pub/broodwar/patches/PC/', keep=False).read())
patches = ['http://ftp.blizzard.com' + match.group(1) for match in re.finditer('<A HREF="(.*?)">', avail) if match.group(1).endswith('.exe')]
latest = sorted(patches, key=lambda x:x.replace('_','-'))[-1]
name = os.path.split(latest)[1]

try:
	print 'Downloading patch', name
	patch = download(latest, overwrite=False)
except OSError:
	if '--force' not in argv or '-f' not in argv:
		print 'Already at the latest version'
		exit(0)
	else:
		patch = download(latest, dryrun=True)
run('wine', patch)
'''

@Installer(default_bottle='starcraft', name="Starcraft: Brood War", version='1.0')
def install(sc):
	sc.settings.EXE = 'C:/Program Files/Starcraft/StarCraft.exe'
	sc.settings.WINEVERSION = '0.9.14'
	sc.settings.update = update

	starcraft = sc.AddInstallSource(cd='setup.exe', name='STARCRAFT', copy_file=True)
	broodwar = sc.AddInstallSource(cd='setup.exe', name='BROODWAR', copy_file=True)

	sc.AddCommand(starcraft)
	sc.AddCommand('move', starcraft, 'c:/Program Files/Starcraft/Starcraft.mpq')
	sc.AddCommand(broodwar)
	sc.AddCommand('move', broodwar, 'c:/Program Files/Starcraft/Broodwar.mpq')
	sc.AddCommand('run','update')

	starcraft_ico = sc.AddIcon(exe='c:/Program Files/Starcraft/StarCraft.exe', name='102')
	sc.AddDesktop('Starcraft: Brood War', starcraft_ico, categories=('Game',))
