#!/usr/bin/env python

from bottle import *

install = 'https://us.battle.net/account/downloads/WoW-4.0.0-WOW-enUS-Installer.exe'
icon = 'http://kde-files.org/CONTENT/content-files/41569-wow-icon-scalable.svg'
bottle_settings = '''
EXE="C:/Program Files/World of Warcraft/Wow.exe"

def install_addon(path):
	bash('unzip', path, '-d', unixpath('c:/Program Files/World of Warcraft/Interface/AddOns'))

def launcher():
	execute('wine', "C:/Program Files/World of Warcraft/Launcher.exe")
'''

wow = Installer('worldofwarcraft'):
wow.AddInstallSource('WoW-Installer.exe', url=install)
wow.AddCommand('WoW-Installer.exe')
wow.settings(bottle_settings)
wow.AddIco('wow.png', url=icon)
wow.AddDesktop('World of Warcraft', 'wow.png', categories='Application;Game;')
wow.AddDesktop('World of Warcraft Launcher', 'wow.png', exe='launcher', categories='Application;Game;')
