#!/usr/bin/env python

from bottle.installer import *

install = 'http://us.media.battle.net.edgesuite.net/downloads/wow-installers/WoW-4.0.0-WOW-enUS-Installer.exe'
icon = 'http://kde-files.org/CONTENT/content-files/41569-wow-icon-scalable.svg'

@Installer(default_bottle='worldofwarcraft', name="World of Warcraft", version='1.0')
def install(wow):
	#These things will be downloaded automatically if they're not in the resources folder.
	#Their return values are paths to the files in question.
	install_exe = wow.AddInstallSource(url=install, name='Wow-Installer.exe')
	wow_svg = wow.AddIcon(url=icon)
	wow.AddCommand(install_exe)
	#Default executable, run with 'bottle worldofwarcraft'
	wow.settings.EXE = 'c:/Program Files/World of Warcraft/Wow.exe'
	#Alternative executables, run with arguments
	wow.settings.launcher = '''execute('wine', 'C:/Program Files/World of Warcraft/Launcher.exe')'''
	wow.settings.install_addon = '''bash('unzip', argv[0], '-d', unixpath('c:/Program Files/World of Warcraft/Interface/Addons'))'''
	wow.AddDesktop('World of Warcraft', wow_svg, categories=('Application','Game'))
	wow.AddDesktop('World of Warcraft Launcher', wow_svg, exe='launcher', categories=('Application','Game'))
#When this block exits, the installer is run. No actions have taken place yet.

